### ISSUE TITLE
 [==> Running parKVFinder for: C:\Program Files (x86)\Anaconda3\Scripts\KV_Files\output\4i8v.pdb Traceback (most recent call last):   File "C:\Users\NINGMEI\AppData\Roaming\pymol\startup\PyMOL2-parKVFinder-Tools\__init__.py", line 283, in run     subprocess.call(self.parKVFinder.text().replace(' ', '\\ '), stdout=subprocess.PIPE)   File "c:\program files (x86)\anaconda3\lib\subprocess.py", line 340, in call     with Popen(*popenargs, **kwargs) as p:   File "c:\program files (x86)\anaconda3\lib\subprocess.py", line 854, in __init__     self._execute_child(args, executable, preexec_fn, close_fds,   File "c:\program files (x86)\anaconda3\lib\subprocess.py", line 1307, in _execute_child     hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by GuodeZhao** [LBC-LNBio/parKVFinder#4] opened 2023-04-25 15:24 UTC
### Setup

 - OS: [e.g. Linux/MacOS/Windows]
 - Python Version: [e.g. v3.x]
 - PyMOL Version: [e.g. v1.8, v2.5]

**Comment by jvsguerra** [comment] 2023-04-25 16:06
Hello @GuodeZhao,

Based on the error message, it looks like you are trying to run [parKVFinder](https://github.com/LBC-LNBio/parKVFinder) on Windows, which is not currently supported by the version of parKVFinder you are using. However, there is a Windows-compatible version of parKVFinder available at https://github.com/LBC-LNBio/parKVFinder-win, which you can try using instead.

I hope this helps. Let me know if you have any further questions or concerns.

**Comment by GuodeZhao** [comment] 2023-04-25 16:21
Thanks



---Original---
From: "João Victor ***@***.***&gt;
Date: Wed, Apr 26, 2023 00:06 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LBC-LNBio/parKVFinder]  [==&gt; Running parKVFinder for: C:\Program Files (x86)\Anaconda3\Scripts\KV_Files\output\4i8v.pdb Traceback (most recent call last):   File "C:\Users\NINGMEI\AppData\Roaming\pymol\startup\PyMOL2-parKVFinder-Tools\__init__.py", line 283, in run     subprocess.call(self.parKVFinder.text().replace(' ', '\\ '), stdout=subprocess.PIPE)   File "c:\program files (x86)\anaconda3\lib\subprocess.py", line 340, in call     with Popen(*popenargs, **kwargs) as p:   File "c:\program files (x86)\anaconda3\lib\subprocess.py", line 854, in __init__     self._execute_child(args, executable, preexec_fn, close_fds,   File "c:\program files (x86)\anaconda3\lib\subprocess.py", line 1307, in _execute_child =?UTF-8?Q?____hp,_ht,_pid,_tid_=3D_=5Fwinapi.CreateProces




 
Hello @GuodeZhao,
 
Based on the error message, it looks like you are trying to run parKVFinder on Windows, which is not currently supported by the version of parKVFinder you are using. However, there is a Windows-compatible version of parKVFinder available at https://github.com/LBC-LNBio/parKVFinder-win, which you can try using instead.
 
I hope this helps. Let me know if you have any further questions or concerns.

**Comment by jvsguerra** [comment] 2023-05-02 13:31
@GuodeZhao, I am closing this issue for now.
If you feel that the issue is still relevant or have any further questions, please feel free to re-open it and provide any additional information that may be helpful in resolving the issue.

**Closed as completed by jvsguerra** 2023-05-02 13:31 UTC
Labels: help wanted
